### ISSUE TITLE
Login window stays black

### ISSUE THREAD

**Issue by Stepptard** [tylerbrawl/Galaxy-Plugin-Rockstar#147]
When I try to connect my accounts only an almost black window appears with the title "Login to Rockstar Games Social Club" but there is nothing to click or fill out.

Window does not appear to be stuck since I can close it by pressing the x in the upper right corner.

**Comment by pinetreeaxe** [comment]
Yup, I had to reinstall the integration and now I can't login ending with the same issue on windows 11.

**Comment by florianleimer** [comment]
Same here, can't connect because it gets stuck on a black window.

**Comment by tylerbrawl** [comment]
As you can probably tell, I'm quite occupied with other work these days; that's why a fix as simple as #149 took as long as it did. Anyways, the issue described by @pinetreeaxe and @florianleimer was fixed in the referenced PR. Galaxy 2.0 should automatically download the update soon.

@Stepptard seems to be describing a different issue, however, since they mention that the window never had any fields to fill out. In contrast, the issue which I just fixed only occurs *after* the user logged into their account. I cannot seem to reproduce their issue, so I'm going to need more details to fix it.

I'll go ahead and close this issue for now. As I mentioned, it may take a few days from the time of writing this for the updates to be downloaded. @Stepptard, if the issue remains after the update is downloaded, then I ask that you submit your log file for the plugin here. After you do that, I can re-open the issue, if necessary.

**Comment by Stepptard** [comment]
Got the new update of GoG Galaxy and the issue persists. I am thankful you're working on this and hope you'll find the time to look into it.

I am pretty unexperienced with git but will do my best to help with information on the bug if you tell me what to look for.

**Comment by tylerbrawl** [comment]
Galaxy 2.0 updates should be separate from those of plugins, as the latter get updated automatically as changes are pushed to the forks of the plugins which @FriendsOfGalaxy maintains. The problem is that they appear to be inactive as of now, so even though a fix technically exists, nobody is getting it.

I really ought to just create a self-contained release for the updated version and ship that under the releases for the plugin. I can do that when I get the time. It's not as convenient as automatic updates, but it's better than nothing, I guess.

**Comment by Stepptard** [comment]
Does this mean there is a fix I can access online? If so could you point me to it? (as I said - pretty new to github)
If not I am happy to wait. Thanks again for working on this.

**Comment by tylerbrawl** [comment]
There is something you can do. In #158, a temporary solution is described. It will take a little DIY work, though.

**Comment by grnassar** [comment]
> Galaxy 2.0 updates should be separate from those of plugins, as the latter get updated automatically as changes are pushed to the forks of the plugins which @FriendsOfGalaxy maintains. The problem is that they appear to be inactive as of now, so even though a fix technically exists, nobody is getting it.
> 
> I really ought to just create a self-contained release for the updated version and ship that under the releases for the plugin. I can do that when I get the time. It's not as convenient as automatic updates, but it's better than nothing, I guess.

This is absolutely a good idea, and probably worth prioritizing if at all possible.  In particular, this plugin is listed (directly, not the FriendsOfGalaxy fork) in the "semi-canonical" https://github.com/Mixaill/awesome-gog-galaxy list that is used by both the Scoop bucket and Slashbunny's plugins updater as the core reference for plugins.  I've created an issue for the Scoop bucket and am preparing a PR for the Slashbunny updater so they point to plugins directly just like their chosen official list does, but that won't do a lot of good in this particular case if the "current release" of this plugin shows as being 0.3.5, from late 2019.
